### ISSUE TITLE
UTL_TEXT missing in install script

### ISSUE THREAD

**Issue by pewu78** [j-sieben/PIT#1]
PIT core check_prerequisites.sql script checks for UTL_TEXT existence and fails because core install.sql script does not call it's installation before (@&core_dir.utl_text/install.sql).

**Comment by pewu78** [comment]
I took the master branch, but I see it's pretty much work in progress / cleanup now ( and there are more important issues to deal with (like cyclic installation dependencies between MSG-PIT_ADMIN-PIT-MSG) so never mind...

**Comment by j-sieben** [comment]
Hi,

if you want to give it a try again, it now should work. To install PIT, you need to install UTL_TEXT first. It’s in a different GitHub repository and is not automatically installed with PIT, as this would require that I double the sources. When branching out a stable install, I will include UTL_TEXT in a matching version with PIT.

**Comment by j-sieben** [comment]
I removed the necessity to install UTL_TEXT alltogether, so simply install PIT and you're done.
