### ISSUE TITLE
Number conversion error in PIT_UTIL

### ISSUE THREAD

**Issue by Stefan-Pz** [j-sieben/PIT#10]
Hi Jürgen,
I proudly created my first test message
`BEGIN
  pit.info( msg.my_first_info_message );
END;`
but the execution ended up in 
[Error] Execution (222: 1): ORA-06502: PL/SQL: numeric or value error: character to number conversion error
ORA-06512: at "PIT_OWNER.PIT_UTIL", line 393    
ORA-06512: at "PIT_OWNER.PIT_PKG", line 234
ORA-06512: at "PIT_OWNER.PIT_PKG", line 262
ORA-06512: at "PIT_OWNER.PIT_PKG", line 284
ORA-06512: at "PIT_OWNER.PIT_PKG", line 815
ORA-06512: at "PIT_OWNER.PIT_PKG", line 896
ORA-06512: at "PIT_OWNER.PIT", line 238
ORA-06512: at line 2

The message is inserted correctly in MSG table (wanted to add a screenshot but this does not work at the moment).
(PSE_ID: 50, PML_NAME: AMERICAN, PMS_ID = PMS_NAME = MY_FIRST_INFO_MESSAGE)

Do you have a clue what's the reason here?

**Comment by j-sieben** [comment]
Hi Stefan,

could you pleas check the package specification of package PIT_UTIL? I’m especially interested in the values of C_TRUE/C_FALSE in lines 25 and 26

Best regards,

Jürgen

**Comment by Stefan-Pz** [comment]
Hi Jürgen, the values in package spec seem ok to me:
C_TRUE constant flag_type := 1;
C_FALSE constant flag_type := 0;

**Comment by j-sieben** [comment]
well, it’s obvious that somewhere there is still a ’N|Y’ pair for boolean values around, as in line 393 a to_bool-method is called. So we need to find the place where this takes place. I will look into this.

**Comment by j-sieben** [comment]
Ok, I found it. You can either re-deploy from Git or simply replace line 393 in package PIT_UTIL with this line:

p_context.trace_timing := to_bool(replace(replace(get_setting(l_args, 3), 'Y', C_TRUE), 'N', C_FALSE));

Reason is that within a context settings there was a hidden ‚Y|N‘ value. This is now allowed but handled in the utility method.

I installed PIT with the respective settings and was able to work with it now:

SQL> set serveroutput on

SQL> begin
  2    pit.set_context('DEBUG');
  3    pit.info(msg.MY_FIRST_MESSAGE);
  4    pit.reset_context;
  5  end;
  6  /

Kontext auf 70|50|1|PIT_CONSOLE gesetzt.
--> Das ist meine erste PIT-Nachricht. Hallo Welt!

**Comment by Stefan-Pz** [comment]
Great, works fine now!
