### ISSUE TITLE
Solution for json_object_t if working with Oracle < 12.1

### ISSUE THREAD

**Issue by Stefan-Pz** [j-sieben/PIT#11]
Hi Jürgen, this time I did not find a new issue;-) I just found out that package PIT_APEX_PKG is invalid due to my DB version 12.1.02 and the JSON_OBJECT_T which was introduced in 12.2 :-(
Unfortunately we will not upgrade in the next months so I would need to apply a workaround.
But if I get it right it's relatively easy to achieve the same with manual string concatenation. The format expected is
[ {"key1":"value1"},...{"key_n":"value_n"} ], then everything should work be fine and I simply pass it over instead of `l_message.stringify`  here:

`pit.log(msg.WEBSOCKET_MESSAGE, msg_args(g_websocket_server, l_message.stringify));
    l_response := apex_web_service.make_rest_request(
                    p_url => g_websocket_server,
                    p_http_method => 'GET',
                    p_body => l_message.stringify());`

If you see any further issues I haven't considered I would appreciate a short note.
Have a nice weekend!
Stefan

**Comment by j-sieben** [comment]
Hi Stefan,

thanks again for pointing this out. I will include your solution by means of conditional compilation, then we’re save here.

Please keep in mind though that the mentioned functionality is not yet working. I simply didn’t find the time to set up a websocket connection yet, plus, I feel that an APEX plugin is necessary to work with the received message in the APEX vicinity. So in general, yes, you’re right, but there is more to it.

Best regards,

Jürgen

**Comment by Stefan-Pz** [comment]
Thanks for committing the solution 👍
