### ISSUE TITLE
After installation packages are invalid

### ISSUE THREAD

**Issue by Stefan-Pz** [j-sieben/PIT#12]
Hi Jürgen, I just dropped the schema and ran the install procedure from your latest Git commits. The installation ended with a success message but I found following issues:

-  ')' is missing in PIT_APEX_PKG  here: 

`pit.log(msg.WEBSOCKET_MESSAGE, msg_args(g_websocket_server, l_message);`

- in PIT_PKG: 
  - component 'NAME_TYPE' must be declared
  - identifier 'G_SCHEMA_NAME' must be declared

During installation I was asked about the values for true, false and the post- and prefixes. The text for the post fix says "Geben Sie einen Wert für false ein" so I guess it is a Copy&Paste issue.

Regards,
Stefan

**Comment by j-sieben** [comment]
Hi Stefan,

that’s of course correct. I copied from a client’s installation didn’t check carefully enough. As I don’t have a 12.1 to install to, this mistake didn’t appear on my machine.

I checked the correction of the script in. Sorry for the inconvenience!

Best regards,

Jürgen

**Comment by Stefan-Pz** [comment]
Big thanks for the quick bugfix, it works now!
