### ISSUE TITLE
[Y/N] is static in PIT_UTIL.check_context_settings

### ISSUE THREAD

**Issue by Stefan-Pz** [j-sieben/PIT#13]
Hello Jürgen,
I think I found one last place where Y/N is not replaced by the values provided in settings:
` C_SETTING_REGEX constant varchar2(200) := '^(((10|20|30|40|50|60|70)\|(10|20|30|40|50)\|(Y|N)\|[A-Z_]+(\:[A-Z_]+)*)|(10\|10\|N\|))$';`

I came across this when I wanted to create my first named context.

**this works fine:**
 BEGIN
pit.set_context( p_log_level      => pit.level_all
                 , p_trace_level    => pit.trace_all
                 , p_trace_timing   => TRUE
                 , p_log_modules    => 'PIT_CONSOLE:PIT_TABLE'
                  );
END;
**this fails:**
BEGIN
  pit_admin.create_named_context(  
      p_context_name   => 'CONTEXT_12'
    , p_log_level      => 70
    , p_trace_level    => 40
    , p_trace_timing   => TRUE
    , p_module_list    => 'PIT_CONSOLE:PIT_TABLE'
   );
END;

Have a good one,
Stefan

**Comment by Stefan-Pz** [comment]
Thanks again for the super fast fix!

**Comment by j-sieben** [comment]
Hi Stefan,

as usual, you’re correct. There is a simple workaround for you, it is sufficient to replace Y|N with 1|0 in the source code. I will adjust this setting in GIT.

best regards,

Jürgen
