### ISSUE TITLE
Obsolete synonyms found

### ISSUE THREAD

**Issue by Nafets-Rezlop** [j-sieben/PIT#14]
Hi Jürgen,
I am preparing my demo to some important guys in order to convince them to integrate PIT into our new Exadata machine. I found the following obsolete syn. in my application schema.
- pit_log (replaced by PIT_TABLE_LOG?)
- PIT_CALL_STACK (to PIT_TABLE_CALL_STACK?)
- PIT_TABLE_CALL_PARAMS  (to PIT_TABLE_PARAMS?)
I hope I have not overlooked anything.
Regards, Stefan

**Comment by j-sieben** [comment]
Hi Stefan,

you’re absolutely correct, I missed deleting the synonyms, I changed them to habe a more straightforward naming convention.

Best regards,

Jürgen

**Comment by Nafets-Rezlop** [comment]
Thanks Jürgen for the quick answer!
