### ISSUE TITLE
UTL_TEXT issue with name of exception

### ISSUE THREAD

**Issue by Nafets-Rezlop** [j-sieben/PIT#15]
Hi Jürgen,
sorry, it' me again with an issue:-) 
In utl_text.**clob_to_blob** the name of the assertion exception does not get adapted to what was setup during the PIT installation (I chose E as prefix).

` when msg.ASSERT_IS_NOT_NULL_ERR then...`

Have a nice day,
Stefan

**Comment by j-sieben** [comment]
Hi Stefan,

I understand this issue but it’s hard to correct other than replacing all exceptions with replacement anchors and reading them from the actual PIT installation. This to me seems to be a little overkill in comparison to refactoring the code quickly…

If you have another idea on how to fix this, please let me know.

Best regards,

Jürgen

**Comment by j-sieben** [comment]
I finally found a way around this. The new version of PIT now allows for any PIT message group to define an error post- or prefix. It defaults to the initially setting but can be overwritten with any value you see fit. So my messages can work with a different exception settings than yours, eliminating the problem alltogether.
