### ISSUE TITLE
Probleme bei der Installation von PIT

### ISSUE THREAD

**Issue by jgcop** [j-sieben/PIT#16]
Hallo Jürgen, erstmal schöne Osterfeiertage.
Wollte heute am Karfreitag PIT installieren, was aber immer an derselben Stelle mit einem Fehler abbricht:
.    - Create default parameters
.    - Script ParameterGroup_PIT
Geben Sie einen Wert für true ein: 'y'
Geben Sie einen Wert für false ein: 'n'
Geben Sie einen Wert für false ein: 'n'
   ,p_par_description => 'Named context, switches logging on [LOG_LEVEL|TRACE_LEVEL|TRACE_TIMING_FLAG ('Y','N')|MODULE_L
IST]'
                                                                                                        *
FEHLER in Zeile 37:
ORA-06550: Zeile 37, Spalte 105:
PLS-00103: Fand das Symbol "Y" als eines der folgenden erwartet wurde:
) , * & = - + < / > at in is mod remainder not rem
<an exponent (**)> <> or != or ~= >= <= <> and or like like2
like4 likec between || multiset member submultiset

Habe es auch mit den Symbolen versucht, die mir als 'erwartet' angezeigt wurden.
Viele Liebe Grüße
Jürgen (Tanto)

**Comment by jgcop** [comment]
Folgende Zeile erzeugt den Fehler:
p_par_description => 'Named context, switches logging on [LOG_LEVEL|TRACE_LEVEL|TRACE_TIMING_FLAG (&C_TRUE.,&C_FALSE.)|MODULE_LIST]'
die Angaben der Runden Klammern  (inklusive dieser) entfernt, dann lief das Skript sauber durch
Viele Liebe Grüße
Jürgen (Tanto)

**Comment by j-sieben** [comment]
Hallo Tanto,

ok, das Problem ist mir zumindest klar. Ich habe diese Stelle geändert, weil ein anderer das Skript mit der Einstellung laufen gelassen hat, boolesche Werte als Ziffern (1, 0) speicher zu wollen. Da gab es Probleme mit dem Context, weil im Context Y/N als Flags standen. Nun habe ich versucht, das wieder modular auf C_TRUE abzubilden, habe aber nun das Problem, dass eine Installation mit Y/N an dieser Stelle ‚Y‘ ersetzt. Das Hochkomma beendet dann die Zeichenkette und ein Fehler ist die Folge. Lass mich einmal sehen, wie ich das lösen kann.

Beste Grüße,

Jürgen

**Comment by j-sieben** [comment]
Aber, hattest Du die aktuelle Version? Ich habe es noch mal mit der Version getestet, die gerade auf GitHub ist, da geht das problemlos. Ansonsten sag mir doch bitte, welcher Skript den Fehler genau enthält.

Beste Grüße,

Jürgen
