### ISSUE TITLE
core/scripts/ParameterGroup_PIT.sql refers to &TRUE. and &FALSE.

### ISSUE THREAD

**Issue by ANDREAS-MARKUS** [j-sieben/PIT#17]
Shouldn't that be &C_TRUE. and &C_FALSE. ? 
Now the install asks for the values to use and crashes on the second FALSE replacement value...

**Comment by j-sieben** [comment]
Hi Andreas,

I don’t fully understand the problem, as I’m able to run the installation script on a new user without issues. What are the settings you’re using, on which OS are you running the script?

Best regards,

Jürgen

**Comment by j-sieben** [comment]
Hi Markus,

I now recall this issue. I was stretched beyond my mental limitations when trying to maintain all these quotation mark issues. Keep in mind that it is also possible to set those to 1 | 0, changing the game again. I hope that I was able to sort those issues out in the actual master.

Thank you anyway for digging into this.

Best regards,

Jürgen

**Comment by ANDREAS-MARKUS** [comment]
No worries! I'll download the current master and try again. We're still trying to get things up-and-running on the Oracle autonomous cloud thingy.
