### ISSUE TITLE
It might be a good idea to abort install when a non-existing Oracle language has been entered

### ISSUE THREAD

**Issue by godzillabytes** [j-sieben/PIT#18]
Hi!
I entered a non-existing language at this point
"Enter default language (Oracle language name) for messages:"

The installation nevertheless continued and but later on gave me some error like "ungueltiger Benutzer" or something similar.
It would be great, if the installer aborts earlier and with a more logical error.

The error was due the init/init.sql script which failed to initialize the INSTALL_USER variable using the following statement due the fact that my chosen language was non existent:
select user sys_user,
       upper('&1.') install_user,
       null remote_user,
       value default_language
  from V$NLS_VALID_VALUES
 where parameter = 'LANGUAGE'
   and value = upper('&2.');

I know this is just convenient feature, so no worries. 

Best regards,

Nils Stritzel

**Comment by j-sieben** [comment]
Sorry for not coming back on this. I added a respective check in the installation script.
