### ISSUE TITLE
Install with existing user and special default tablespace

### ISSUE THREAD

**Issue by fraenkg** [j-sieben/PIT#21]
Hallo Jürgen,

bei einer Neuinstallation ist mir folgendes aufgefallen:
Voraussetzungen:
- separates tablespace (create tablespace TS_SU_ALL Datafile ....)
- neuer Benutzer (create user SUTLS identified by "pswd" default tablespace TS_SU_ALL ...)
- Berechtigung (grant connect to SULTS)

Ein Aufruf des Installationsskriptes mittels @pit_install SUTLS GERMAN führt erst mal zu einem Fehler in "chek_users_exist.sql". Dort kann der Identifizierer "l_user_has_quota" nicht aufgelöst werden. Nach dem Ersetzen von "l_user_has_quota" durch "l_user_has_tablespace" war das Problem behoben.
Allerdings scheiterte ein weiterer Versuch jetzt daran, dass die Tabelle "parameter_group" im Skript "parameter_group.tbl" wegen nicht ausreichender Berechtigung nicht angelegt werden konnte (ORA-01950: keine Berechtigungen für Tablespace 'TS_SU_ALL'). Der Grund dafür besteht darin, dass im Skript "chek_users_exist.sql" quotas für das tablespace "users" erzeugt werden, nicht aber für das default tablespace des Benutzers.

Mein Vorgehen für eine gelungene Installation besteht also jetzt darin, dass ich a)  in "chek_users_exist.sql" den Bezeichner "l_user_has_quota" durch "l_user_has_tablespace" ersetze und b) beim Anlegen des Benutzers die quotas für das default tablespace vorher festlege.

Vermutlich ist mein Vorgehen bei der Installation nicht der allgemein beschrittene Pfad, aber vielleicht lässt sich auch hierfür noch eine kleine Verbesserung etablieren.

Viele Grüße und besten Dank für die hervorragenden Werkzeuge,
Frank

**Comment by fraenkg** [comment]
Kleiner Nachtrag: War mir grade schon wieder entfallen, aber ich habe im Skript "chek_users_exist.sql" noch eine kleine Änderung vorgenommen. In Zeile 34 ist  "user" durch "username" ersetzt worden ("where username = upper('&1.')". Ohne dem wurde immer versucht den bestehenden Benutzer erneut anzulegen.
Ich habe nicht untersucht, ob es etwas damit zu tun haben kann, dass ich in einer PDB arbeite.
Was mich allerdings verwundert hat, ist die Tatsache dass "select * from dba_ts_quotas where user = 'SUTLS';" keiner Fehler generiert und einfach eine leere Ergebnismenge liefert, obschon dieser view keine Spalte mit dem Namen "USER" bereistellt.

**Comment by j-sieben** [comment]
Hallo Frank,

herzlichen Dank für den Hinweis zum Fehler. Ich habe das natürlich sofort korrigiert.

Zu Deinen Mails: 
1. Das Skript check_user_exists.sql erteilt nur dann ein Quota auf den DEFAULT_TABLESPACE, wenn der Benutzer überhaupt keinen Quota besitzt. Dann allerdings nehme ich den allgemeinen Default Tablespace und nicht den des aktuellen Benutzers. Vielleicht könnte ich das noch verbessern, allerdings ist es schon etwas schräg, einem Benutzer einen Default Tablespace, aber keinen Quota hierauf zu erteilen … Ich sehe mir das aber noch einmal an.

2. USER, das ist das hinterhältige, ist eine SQL-Funktion und liefert den angemeldeten Benutzer. Daher brauch keine Spalte dieses Namens zu existieren, es wird einfach der angemeldete Benutzer mit SUTLS verglichen. Das führt zwar wohl zu keinem SQL-Fehler, aber auch nicht zum gewünschten Verhalten.

Beste Grüße,

Jürgen

**Comment by fraenkg** [comment]
Hallo Jürgen,

vielen Dank für die schnelle Beantwortung und Korrektur.

Die Schrägheit bezüglich der Quota ist nicht zu leugnen. Aber ich bin halt faul. Bei bei der Sichtung der Quellen sah ich, dass darauf geprüft wird und ggf. auch  Quota vergeben werden. Daher glaubte ich mir das sparen zu können. Leider hatte ich nicht genau genug nachgeforscht.

Mein eigentliches Anliegen war lediglich alle PIT- Objekte in einem gesonderten Tablespace anzulegen. Da ich eine entsprechende Parametrisierung nicht gefunden habe, legte ich eben den Benutzer mit Default Tablespace an.  Später habe ich gesehen, dass im Skript "settings.sql" ein Kommentar vorhanden ist, der zeigt wie ein Default Tablespace festgelegt werden kann. Aber dazu müsste dann auch die Datei verändert werden. Ein Parameter wäre sicher einfacher im Gebrauch.

Und das mit der USER- Funktion - ehrlich - da hätte ich auch selber drauf kommen können. War wohl gestern nicht mein bester Tag.

Viele Grüße aus Berlin,
Frank

**Comment by j-sieben** [comment]
Hallo Frank,

ja, es wäre möglich, dazu einen Parameter zu erstellen, aber in den Settings kannst Du ja auch festlegen, wie der FLAG_TYPE aussehen soll, daher halte ich es für akzeptabel, dort auch den Tablespace einzustellen.
Normalerweise ist die Einstellung ja dann nicht erforderlich, wenn der Benutzer entsprechend angelegt wurde. Ich hätte damit auch Folgeprobleme, so werden ja eventuell mehrere Benutzer angelegt für PIT selbst, dann für die APEX-Anwendung etc. Ich müsste dort überall mit den Tablespaces umgehen, da bin ich halt eher faul … ;-)

Ich werde aber die Doku zur Installation um diesen Punkt erweitern, um die Informationen wenigstens nicht nur durch Quellenstudium der Installationsdateien erhalten zu können. Besten Dank daher für die Schilderung dieser Problemsituation.

Beste Grüße,

Jürgen

**Comment by j-sieben** [comment]
Ich habe in der Zwischenzeit die Installationsskripte so umgestellt, dass der Tablespace als Parameter übergeben werden kann. Wird kein Parameter übergeben, wird der Tablespace aus den Benutzereinstellungen dynamisch ermittelt.
