### ISSUE TITLE
Issue with type spec PIT_UTIL 

### ISSUE THREAD

**Issue by Stefan-Pz** [j-sieben/PIT#26]
Dear Jürgen
thanks for reworking the installation grants for PIT, this will help to introduce it a lot in my company.
Unfortunately while installing it always fails due to invalid PIT_MODULE spec. 
I also tried to manually compile all type specs but this also failed.
Anyway, happy easter, see you at APEX Connect!
Stefan 

.    - Create type specificationPIT_MODULE_LIST
**  Create ADMIN package declarations
.    - Create package specification pit_util

Fehler fⁿr TYPE PIT_OWNER.PIT_MODULE:

LINE/COL ERROR
-------- -----------------------------------------------------------------
0/0      PL/SQL: Compilation unit analysis terminated
1/11     PLS-00304: Body von 'PIT_MODULE' nicht ohne die Spezifikation kompilierbar
`

**Comment by j-sieben** [comment]
Hi Stefan,

I looked into this issue and it was caused by a logic problem if no database version 23c is present. I corrected the issue. Could you please try again? Installation should now work.

Best regards

Jürgen
