### ISSUE TITLE
Consider alter session command for 23c while installing client

### ISSUE THREAD

**Issue by Stefan-Pz** [j-sieben/PIT#27]
Dear Jürgen,
there is a similar issue when granting privs to a client.

>> alter session set plsql_implicit_conversion_bool = true
Error at line 9
ORA-02248: invalid option for ALTER SESSION

Connected PIT_OWNER

********************************************************************************
*** Grant access to PIT to client DEV

**  Grant access to PARAM installation

**  Granting access to parameter package to DEV
*   Grant access rights to DEV
Script stopped on line 8 of ...git\pit\PIT\install_scripts\../parameters/grant_client.sql.

**Comment by j-sieben** [comment]
Hi Stefan,

it’s true, that there ist an exception, but this is to be expected and did not stop the installation obviously. Could you please send me the whole write out of the script to allow me to look into the problem? The script runs fine on my side on a 21c.

Beste Grüße

Jürgen

**Comment by Stefan-Pz** [comment]
I fear it's my issue then, I also had an issue while executing the .bat file and changed paths and so on in the Sql files. Let me check this again...
