### ISSUE TITLE
Fehler bei der Installation (Oracle Express 19) 03.07.2020 

### ISSUE THREAD

**Issue by jgcop** [j-sieben/PIT#3]
Fehler anfang:
.    - Create package Body PIT_ADMIN

Warnung: Package Body wurde mit Kompilierungsfehlern erstellt.

Fehler bei PACKAGE BODY PIT_ADMIN:

LINE/COL ERROR
-------- -----------------------------------------------------------------
988/7    PL/SQL: Statement ignored
988/25   PLS-00201: ID 'MSG.SQL_ERROR' muss deklariert werden
.    - Create default parameters
.    - Create translatable items
begin
*
FEHLER in Zeile 1:
ORA-04063: package body "PIT_OWNER.PIT_ADMIN" enth├ñlt Fehler
ORA-06508: PL/SQL: aufgerufene Programmeinheit : "PIT_OWNER.PIT_ADMIN" konnte nicht gefunden werden
ORA-06512: in Zeile 3

Grüße
Jürgen (aus Berlin ;-) )

**Comment by j-sieben** [comment]
Error was sorted out
