### ISSUE TITLE
Neuer Fehler

### ISSUE THREAD

**Issue by razorTwo** [j-sieben/PIT#4]
Folgende Fehlermeldung bekomme ich bei der Installation von PIT:
Fehler f³r PACKAGE BODY UTILS.PIT_ADMIN:

LINE/COL ERROR
-------- -----------------------------------------------------------------
790/16   PL/SQL: Item ignored
790/16   PLS-00201: ID 'WWV_FLOW_GLOBAL.VC_ARR2' muss deklariert werden
799/7    PL/SQL: Statement ignored
799/7    PLS-00320: Die Typ-Deklaration dieses Ausdruckes ist unvollstõndig oder fehlerhaft
800/7    PL/SQL: Statement ignored
800/31   PLS-00320: Die Typ-Deklaration dieses Ausdruckes ist unvollstõndig oder fehlerhaft
801/7    PL/SQL: Statement ignored
801/16   PLS-00320: Die Typ-Deklaration dieses Ausdruckes ist unvollstõndig oder fehlerhaft
.    - Create default parameters

greets
tanto

**Comment by razorTwo** [comment]
oracle 19.3 und APEX 20.1

**Comment by j-sieben** [comment]
Dependency from APEX has been removed from PIT_ADMIN, so the issue should be gone now.
