### ISSUE TITLE
Initial thoughts and questions

### ISSUE THREAD

**Issue by S-Koell** [j-sieben/PIT#5]
Learned about PIT yesterday and I'm really impressed. Love what you've build here!
I thought I already have high standards with ORA Logger but you put it to the next level :D 

But after reading through the doc I have some questions and thoughts. (Important: I haven't installed or used PIT yet!)

- As far as I understood you have to define the severity for a message. But I only see log procedures which override this and dont have variable level?! E.g.: debug | Captures debug information, level debug. 
So the severity of the msg will be ignored? Do I miss something?
- How to handle the messages with multiple development environments. E.g. keep all the pit_admin.merge_messages in a script which can be version controlled and therefore merged and called on every instance?!
- Some procedure names are in my opinion not self explanatory, eg.: "stop" (handles an error and calls leave and re-raises the error). This info needs to be in the name in my opinion, eg. "leave_and_raise"
- Option to log msg_params without calling "enter" or "leave" which would switch the context. 
- Is there a way to raise exception with raise_application_error and the correct message? Sth like pit.raise(msg.CHILD_RECORD_FOUND_ERR)? Or should this be done with pit.sql_exception? 

Maybe some bad questions but as I said I just had a first look :)

**Comment by j-sieben** [comment]
Hi Sebastian,

thank you for your interest in PIT. I’ll answer your questions in the cite block.

PIT has proven to be useful in many projects in the meantime and it is based on many of my other utilities, like my Finite State Machine implementation. If you dig into this project, you will find examples of the versatility of PIT.

I don’t find your questions bad by any means and I kindly invite you to share your thoughts on the project with me.

Best regards

ConDeS GmbH & Co. KG
Jürgen Sieben

Mühlenstraße 229
41236 Mönchengladbach

Phone: +49-2166-12 44 33



> Am 16.10.2020 um 10:34 schrieb Sebastian Köll <notifications@github.com>:
> 
> 
> Learned about PIT yesterday and I'm really impressed. Love what you've build here!
> I thought I already have high standards with ORA Logger but you put it to the next level :D
> 
> But after reading through the doc I have some questions and thoughts. (Important: I haven't installed or used PIT yet!)
> 
> As far as I understood you have to define the severity for a message. But I only see log procedures which override this and dont have variable level?! E.g.: debug | Captures debug information, level debug.
> So the severity of the msg will be ignored? Do I miss something?
Basically the verbose API is meant to reduce the amount of parameters required. And yes, it overrides the severity of the message. The message severity is planned to be used with the more generic method pit.LOG. I felt that this approach is a little more intuitive: If you say pit.ERROR, you want PIT to raise an exception, no matter what the severity of the message is. If, on the other side, you simply say pit.LOG, the message severity will be taken into account. The severity of the message plays a role in cleaning up the environment as well: You may choose to purge only messages with severity LEVEL_DEBUG and less.
> How to handle the messages with multiple development environments. E.g. keep all the pit_admin.merge_messages in a script which can be version controlled and therefore merged and called on every instance?!
Yes. PIT_ADMIN offers a method to export message groups as ZIP files. This is ideally suited in conjunction with the PIT-APEX application, which is planned to be utilized on the development environment only. Once set up, you can easily export all parameters, messages and translatable items as separate files per group and write them to a version control system. The files include calls to the PIT admin API to allow for easy deployment.
> Some procedure names are in my opinion not self explanatory, eg.: "stop" (handles an error and calls leave and re-raises the error). This info needs to be in the name in my opinion, eg. „leave_and_raise“
I’m sorry to hear that, as I really liked PIT.STOP ;-). You may obviously change that to your liking but … In a way I feel that the method tells you what it does: It stops the execution of the code and handles the internals of PIT.
> Option to log msg_params without calling "enter" or "leave" which would switch the context.
I don’t get what you mean by „switch context“. As it stands now, there is an object called CALL_STACK_TYPE that allows to store the method that was called along with the params the method was called with. Plus, it allows to store the result of out parameters or return values. The interface to call it are the ENTER- and LEAVE-methods. I wonder what the context of MSG_PARAMS would be without calling these methods? But I’m open to improvement here if you let me know your concrete use case for this.
> Is there a way to raise exception with raise_application_error and the correct message? Sth like pit.raise(msg.CHILD_RECORD_FOUND_ERR)? Or should this be done with pit.sql_exception?
No, PIT.SQL_EXCEPTION is used to capture errors, like PIT.STOP does, but with difference that if handles the exception and proceed with the code (a better name would be beneficial here, I guess). If you want to raise an exception, you simply call PIT.ERROR, along with the name of the message. Your example suggests a different use though: Create a message called CHILD_RECORD_FOUND and map it to error number -2292. If you then try to delete a row with a FK reference to it, the database will throw this error and you simply catch it within the exception block with WHEN msg.CHILD_RECORD_FOUND_ERR THEN. Make sure to name this message generic enough to be reusable in other use cases, at is is possible to map an Oracle error number only once.

**Comment by S-Koell** [comment]
Thanks for the quick answer!

>PIT has proven to be useful in many projects in the meantime and it is based on many of my other utilities, like my Finite State Machine implementation. If you dig into this project, you will find examples of the versatility of PIT.

Will do :)

> Basically the verbose API is meant to reduce the amount of parameters required. And yes, it overrides the severity of the message. The message severity is planned to be used with the more generic method pit.LOG. I felt that this approach is a little more intuitive: If you say pit.ERROR, you want PIT to raise an exception, no matter what the severity of the message is. If, on the other side, you simply say pit.LOG, the message severity will be taken into account. The severity of the message plays a role in cleaning up the environment as well: You may choose to purge only messages with severity LEVEL_DEBUG and less.

Okay I have overlooked pit.LOG because it wasn't in the plsqldoc (PIT/Doc/DOAG/pit.html).


> I don’t get what you mean by „switch context“. As it stands now, there is an object called CALL_STACK_TYPE that allows to store the method that was called along with the params the method was called with. Plus, it allows to store the result of out parameters or return values. The interface to call it are the ENTER- and LEAVE-methods.

I shouldn't have used the word "context" because of the special meaning in Oracle.
What I meant: You keep track of the hierarchy (which I meant by context previously) with the enter and leave methods. There is no other way to store the msg_params as far as I see. So if I need to store "params" I have no way to do it without messing with the hierarchy. (example after the next quote)

> I wonder what the context of MSG_PARAMS would be without calling these methods? But I’m open to improvement here if you let me know your concrete use case for this.

With Ora Logger I sometimes had the following approach:
I have computed some data which is in variables and I want to store them as debug in the log (e.g. for checking the values after running the code).
I then would 
```
logger.append_param(l_params, 'l_rec_type.row1', l_row_type.row1);
logger.append_param(l_params, 'l_rec_type.row2', l_row_type.row2);
logger.append_param(l_params, 'l_rec_type.row3', l_row_type.row3);
logger.log('Webservice Call Success', l_scope, null, l_params);
```
This way I can not only track the input parameters but also the local variables within a proc/func.
I think I could use a normal "pit.log" with replacement args .. but thats not dynamic. With OraLogger I can add/remove variables without touching the logger call. Imagine in the example above I add fields to the record. I wouldnt need to change the logger call instead I just add one "append param".
With pit (as far as I understood) I would need to change the msg and also add a substituiton text.
Or what happens if I provide more args as defined in the msg?


> No, PIT.SQL_EXCEPTION is used to capture errors, like PIT.STOP does, but with difference that if handles the exception and proceed with the code (a better name would be beneficial here, I guess). If you want to raise an exception, you simply call PIT.ERROR, along with the name of the message. Your example suggests a different use though: Create a message called CHILD_RECORD_FOUND and map it to error number -2292. If you then try to delete a row with a FK reference to it, the database will throw this error and you simply catch it within the exception block with WHEN msg.CHILD_RECORD_FOUND_ERR THEN. Make sure to name this message generic enough to be reusable in other use cases, at is is possible to map an Oracle error number only once.

I used the example of the Doc but you are right - it doesn't fit because I was talking about user defined exceptions.
So for raising user defined errors we should use pit.error. Okay understood - but once again I have to complain about words :D 
It's not clear that pit.error is raising anything. Looks like a normal log procedure. Same with "fatal".
I would expect a "pit.raise" and maybe you can decide in the msg if the severity is fatal or error. But the behaviour of the db is the same for both as far as I see ... you raise an exception.

**Comment by S-Koell** [comment]
>PIT has proven to be useful in many projects in the meantime and it is based on many of my other utilities, like my Finite State Machine implementation. If you dig into this project, you will find examples of the versatility of PIT.

pit.stop only tells me that it stops sth with pit. Not that it is stopping the code or anything.
pit.leave also doesnt leave a procedure. The end of the proc does that or the return.

My point is: if you are really changing the flow of a program it should be crystal clear. And everybody knows what a raise does.
A stop can be stopping of logging, of tracing, anything ...

**Comment by j-sieben** [comment]
Hi Sebastian,

I got your point regarding the requirement to log variables. It is quite easy to achieve and I will incorporate this into PIT soon. I guess I will offer a method called LOG_PARAMS, allowing you to define a MSG_PARAMS instance as its payload. This way, you can log as many parameters as you like everywhere you like.

Sorry, the PLSQL-Doc may be a bit outdated, I need to refresh this. In regard to the naming of the method, I feel that there are always arguments for both sides. I maybe stick to my naming because I’m used to it and it would take some effort to change it. The method names were chosen based on earlier frameworks I investigated and this may be a consequence as well.
It is not much work for you to change it, though: PIT is the API to the functionality. Little intelligence sits within that package, it mainly serves as a wrapper around PIT_PKG where the real work is done. So why not simply clone PIT and rename their methods to your liking? As this package rarely changes, this won’t be a risky thing to do.

Best regards,

Jürgen
