### ISSUE TITLE
Can we use PIT on the Oracle Cloud ATP? 

### ISSUE THREAD

**Issue by ANDREAS-MARKUS** [j-sieben/PIT#6]
Hello, we were trying to install PIT on the Oracle-Always-Free-Cloud-ATP database instance, but it seems that the admin user is not allowed to log in as sysdba. We see the same problems with Logger for example. Maybe you have already tried this yourself?

**Comment by j-sieben** [comment]
Hi Andreas,

this request has come across several times. I guess it is doable, probably even without rewriting the installation scripts. I’d try and run the scripts directly (not via the shell script or the batch) by connecting as the DBA user and run script PIT_INSTALL.sql directly. Just provide the username and the default langauge and see what happens. It may be that some grants are missing, such as DBMS_CRYPTO for the PIT_MAIL package, but overall I wuld guess that a DBA user would be able to run the script. 

I don’t tried this myself, so it would be nice if you could inform me about the process.

Rewriting the install scripts to allow installing PIT without a DBA account is a longwinded process. It could be done, but the requirements to get the respective grants will not disappear obviously. So if you can make sure that the grants are in place, I might consider looking into this.


BBest regards,

Jüregn Sieben

**Comment by ANDREAS-MARKUS** [comment]
Thanks! We will try. When we succeed, we'll let you know how we did it!
