### ISSUE TITLE
old code examples in using_pit.md 

### ISSUE THREAD

**Issue by Stefan-Pz** [j-sieben/PIT#9]
Hey Jürgen,
while proceeding with my demo (to convince our architect and chief developer) I found two small issues in [this subchapter](https://github.com/j-sieben/PIT/blob/master/Doc/using_pit.md#handling-log-messages-and-debugging-with-pit)

1. the MERGE_MESSAGE procedure has new parameter names
2. the TRANSLATE_MESSAGE does not exist any more. I assume that I can use the merge_message and just provide another language to translate (at least this worked for me, I hope this is the intended way)
3. a typo in parameter name:
`pit.enter('my_func', 
    p_ oparams => msg_params(`

Enjoy the rest of your day,
Stefan

**Comment by j-sieben** [comment]
Hi Stefan,

(1) has been fixed, as the other occurences  as well
(2) is a typo: This method is in PIT_ADMIN.

Thanks for pointing that out and good luck when convincing your colleagues!

Best regards

Jürgen

**Comment by Stefan-Pz** [comment]
Thanks for the super fast fix again.
